# Generated by Django 5.2.17 on 2026-09-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.CharField(blank=True, choices=[('test', 'Test')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(blank=True, choices=[('trial/pro', 'Tril Pro'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_notification',
            field=models.BooleanField(default=False),
        ),
    ]
