# Generated by Django 5.2.17 on 2026-09-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_categories_profile_email_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.CharField(blank=True, choices=[('real_estate_rent', '🏠 Оренда житла'), ('real_estate_roommate', '🛏 Пошук сусіда / кімнати'), ('vnz_and_residence', '📑 ВНЖ, ПМЖ та Терміни'), ('documents_and_translations', '✍️ Переклади та Довідки'), ('legal_and_lawyers', '⚖️ Юристи та Право'), ('accounting_and_taxes', '📊 Бухгалтерія та Податки'), ('construction_and_masters', '🧱 Будівництво та Майстри'), ('home_repair_and_cleaning', '🛠 Ремонт дому та Клінінг'), ('tech_and_gadget_repair', '💻 Ремонт техніки та ПК'), ('logistics_and_moving', '🚚 Вантажні перевезення'), ('errands_and_delivery', '📦 Дрібні посилки та Ліки'), ('auto_repair_and_care', '🚗 СТО та Детейлінг'), ('childcare_and_nanny', '👶 Няні та Догляд за дітьми'), ('medical_and_health', '🩺 Лікарі та Медицина'), ('veterinary_and_pets', '🐾 Ветеринари та Тварини'), ('education_and_tutors', '🎓 Репетитори та Мови'), ('it_and_digital', '🌐 IT, Боти та Сайти')], default=None, max_length=100, null=True),
        ),
    ]
