# Generated by Django 5.2.17 on 2026-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
