# Generated by Django 5.2.17 on 2026-09-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tg_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
