# Generated by Django 5.2.17 on 2026-09-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_telegram_id_profile_tg_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
    ]
