# Generated by Django 5.2.17 on 2026-09-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_email_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
